env:
  browser: true
  node: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
  sourceType: module
  tsconfigRootDir: ./
  ecmaFeatures:
    jsx: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:react/recommended
  - prettier
  - plugin:prettier/recommended
  - plugin:react-hooks/recommended
  - plugin:lodash/recommended
  - ./.imports.eslintrc.js
plugins:
  - "@typescript-eslint"
  - react-hooks
  - react
  - prettier
  - eslint-plugin-import-helpers
  - lodash
rules:
  semi: 2
  quotes:
    - error
    - single
    - avoidEscape: true
  arrow-parens:
    - error
    - as-needed
  "@typescript-eslint/interface-name-prefix": off
  "@typescript-eslint/member-delimiter-style": off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/ban-ts-ignore": off
  "@typescript-eslint/no-unsafe-call": off
  "@typescript-eslint/no-unsafe-assignment": off
  "@typescript-eslint/no-unsafe-member-access": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/ban-types": off
  "@typescript-eslint/no-var-requires": off
  "@typescript-eslint/no-empty-interface": off
  react/prop-types: off
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  yoda: error
  prettier/prettier:
    - error
    - endOfLine: auto
  jsx-quotes:
    - error
    - prefer-double
  react/display-name: warn
  react/jsx-uses-vars: error
  react/destructuring-assignment:
    - error
    - always
    - ignoreClassFields: true
  react/self-closing-comp:
    - error
    - component: true
      html: true
  react/forbid-component-props:
    - error
    - forbid:
      - style
      - className
  react/forbid-dom-props:
    - error
    - forbid:
      - style
      - className
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react/no-access-state-in-setstate: error
  react/no-array-index-key: warn
  react/no-multi-comp:
    - error
    - ignoreStateless: true
  react/jsx-boolean-value:
    - error
    - never
  react/jsx-curly-brace-presence: error
  react/jsx-fragments:
    - error
    - element
  react/jsx-no-constructed-context-values: error
  react/jsx-no-useless-fragment: error
  react/jsx-pascal-case: error
settings:
  import/resolver:
    typescript: {}
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
  react:
    version: detect
