plugins:
  - stylelint-prettier
  - stylelint-declaration-use-variable
  - stylelint-a11y
  - stylelint-high-performance-animation
extends:
  - stylelint-prettier/recommended
  - stylelint-config-recommended
  - stylelint-config-styled-components
processors:
  - stylelint-processor-styled-components
rules:
  prettier/prettier: true
  sh-waqar/declaration-use-variable:
    - /color/
    - font
    - box-shadow
    - transition
    - font-family
  plugin/no-low-performance-animation-properties:
    - true
    - ignore: paint-properties
  a11y/no-text-align-justify: true
  a11y/selector-pseudo-class-focus: true
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown: true
  function-name-case: lower
  value-keyword-case: lower
  max-nesting-depth: null
  selector-max-id: null
  selector-max-compound-selectors: null
  order/properties-alphabetical-order: null
  declaration-property-value-disallowed-list: null
  time-min-milliseconds: 150
  no-duplicate-selectors: true
  no-eol-whitespace: true
  no-empty-first-line: true
  selector-descendant-combinator-no-non-space: true
  property-no-vendor-prefix: true
  font-weight-notation: numeric
  selector-combinator-space-before: always
  selector-combinator-space-after: always
  font-family-name-quotes: always-unless-keyword
  function-whitespace-after: always
  rule-empty-line-before:
    - always
    - except:
        - first-nested
